# Generated by Django 2.2.8 on 2020-03-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Is this shortened link disabled?'),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='is_spam',
            field=models.BooleanField(default=False, help_text='Is this link considered spam and disabled?'),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='slug',
            field=models.SlugField(),
        ),
    ]
