# Generated by Django 2.2.8 on 2020-03-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20200304_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShortUrlMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('short_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='shortener.ShortUrl')),
                ('user_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.UserAgent')),
            ],
        ),
    ]
