# Generated by Django 2.2.8 on 2020-03-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shorturlmetadata_useragent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=512)),
                ('is_spam', models.BooleanField(default=True)),
            ],
        ),
    ]
