# Generated by Django 2.2.8 on 2020-03-04 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_blacklisteddomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturlmetadata',
            name='date',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
