# Generated by Django 2.2.8 on 2020-03-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20200304_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragent',
            name='user_agent',
            field=models.TextField(unique=True),
        ),
    ]
