# Generated by Django 2.2.10 on 2021-03-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20200304_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='human_created',
            field=models.BooleanField(default=False, help_text='Was created by a human', null=True),
        ),
    ]
